Resources:
# Deploy Bastion Server #########################################################
  BastionServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0888db1202897905c
      SubnetId: !ImportValue PublicSubnetVPC2BastionId
      SecurityGroupIds:
        - !ImportValue BastionSecurityGroupId
      KeyName: vockey
      BlockDeviceMappings:
        - DeviceName: /dev/sda1  
          Ebs:
            VolumeSize: 50       
            VolumeType: gp2      
      Tags:
        - Key: Name
          Value: FinsecureBastion2





# Launch template for web servers ######################################33



  webServersFinsecureTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: webServersFinsecureTemplate
      LaunchTemplateData: 
        InstanceType: t3.small
        ImageId: ami-0a5c3558529277641
        KeyName: vockey
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: 0
            Groups:
              - !ImportValue WebServerSecurityGroupId 
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            apt update -y
            apt install apache2
            apt install php8.3
            apt-get install -y php8.3-cli php8.3-common php8.3-mysql php8.3-zip php8.3-gd php8.3-mbstring php8.3-curl php8.3-xml php8.3-bcmath
            apt install git
            systemctl start apache2
            systemctl enable apache2 
            git clone https://github.com/AlexM208/501AZ_FsecurePhpServerCode.git
            cd 501AZ_FsecurePhpServerCode/
            cp PDOFsecure.php ../../../var/www/html/
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 20
              VolumeType: gp2

            #git clone ////repo
            #cd repo
            #cp filename destination    ../../../var/www/html/

# Auto Scaling group ############################################33

  WebServerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue WebServer01PublicSubnetVPC2Id
        - !ImportValue WebServer02PublicSubnetVPC2Id
        - !ImportValue WebServer03PublicSubnetVPC2Id
        - !ImportValue WebServer04PublicSubnetVPC2Id
      LaunchTemplate:
        LaunchTemplateId: !Ref webServersFinsecureTemplate
        Version: !GetAtt webServersFinsecureTemplate.LatestVersionNumber
      MinSize: 2
      MaxSize: 3
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref WebServerTargetGroup

# Target group ############################################

  WebServerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue VPC2Id
      TargetType: instance

# Application load balancer ############################3

  WebServerLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: WebServerALB
      Scheme: internet-facing
      Subnets:
        - !ImportValue WebServer01PublicSubnetVPC2Id
        - !ImportValue WebServer02PublicSubnetVPC2Id
        - !ImportValue WebServer03PublicSubnetVPC2Id
        - !ImportValue WebServer04PublicSubnetVPC2Id
      SecurityGroups:
        - !ImportValue WebServerSecurityGroupId
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
    
  WebServerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebServerTargetGroup
      LoadBalancerArn: !Ref WebServerLoadBalancer
      Port: 80
      Protocol: HTTP













######################################################## Outputs  ########################################################

Outputs:

  PublicBastionIp:
    Description: Public IP address of the Bastion instance
    Value: !GetAtt BastionServer.PublicIp





  WebServerLoadBalancerDNS:
    Description: DNS name of the Load Balancer for Web Servers
    Value: !GetAtt WebServerLoadBalancer.DNSName

##### Auto Scaling group ########################################################





# ########################################################













#########################################################











#########################################################